### ISSUE TITLE
1. 생성자 대신 정적 팩터리 메서드를 고려하라

### ISSUE THREAD

**Issue by Kimjaeyeon518** [Bigin-Study/effective-java#1]
(ex)
```
public static Boolean valueOf(boolean b) {
    return b ? Boolean.TRUE : Boolean.FALSE;
}
```

### 장점

1. 이름을 가질 수 있다 

- 생성자에 넘기는 매개변수와 생성자 자체만으로는 반환될 객체의 특성을 제대로 설명하지 못하지만, 적절한 네이밍으로 이를 쉽게 묘사할 수 있다.

2. 호출될 때마다 인스턴스를 새로 생성하지는 않아도 된다.

- 불변 클래스와 같이 인스턴스를 캐싱하여 재활용할 수 있는 클래스가 있을 때 (특히 생성 비용이 큰), 이런 객체가 자주 요청되는 상황이라면 성능을 상당히 끌어올려줄 수 있다.

3. 반환 타입의 하위 타입 객체를 반환할 수 있는 능력이 있다.

- 반환할 객체의 클래스를 자유롭게 선택할 수 있게 하는 '엄청난 유연성'이 생긴다. 이를 응용하면 API 를 만들 때 구현 클래스를 공개하지 않고도 그 객체를 반환할 수 있어 API 를 작게 유지할 수 있다.

4. 입력 매개변수에 따라 매번 다른 클래스의 객체를 반환할 수 있다.

- 반환 타입의 하위 타입이기만 하면 어떤 클래스의 객체를 반환하든 상관없고 심지어 또 다른 클래스의 객체를 반환할 수도 있다.

(ex)
```
public class Item{

    public static Item getItemByType(String type){
        if(type.equals("ONLINE"){
            return new OnlineItem();
        } else if(type.equals("DEPARTMENT_STORE")){
            return new DptsItem();
        }
        
        new IllegalArgumentException("잘못된 타입입니다.");
    }

}
```

5. 정적 팩터리 메서드를 작성하는 시점에는 반환할 객체의 클래스가 존재하지 않아도 된다.

- 인터페이스나 클래스가 만들어지는 시점에서 하위 타입의 클래스가 존재 하지 않아도 나중에 만들 클래스가 기존의 인터페이스나 클래스를 상속 받으면 언제든지 의존성을 주입 받아서 사용이 가능하다.

(ex)
```
public class TicketStore { 
	/** TicketSeller는 인터페이스이고 구현체가 없음에도 아래와 같은 메서드 작성이 가능하다.**/ 
	public static List<TicketSeller> getSellers(){ 
		return new ArrayList<>(); 
	} 
}
```

### 단점

1. 상속을 하려면 public 이나 protected 생성자가 필요하니 정적 팩터리 메서드만 제공하면 하위 클래스를 만들 수 없다.

- 컬렉션 프레임워크의 유틸리티 구현 클래스들은 상속할 수 없다는 뜻. 어찌 보면 이 제약은 상속보다 컴포지션을 사용하도록 유도하고, 불변타입으로 만들려면 이 제약을 지켜야 한다는 점에서 오히려 장점으로 받아들일 수도 있다.

2. 정적 팩터리 메서드는 프로그래머가 찾기 어렵다.

### 정적 팩터리 메서드에서의 명명 방식

1. from : 매개변수를 하나 받아서 해당 타입의 인스턴스를 반환하는 형변환 메서드
(ex) `Date d = Date.from(instant);`

2. of : 여러 매개변수를 받아 적합한 타입의 인스턴스를 반환하는 집계 메서드
(ex) `Set<Rank> faceCards = EnumSet.of(JACK, QUEEN, KING);`

3. valueOf : from 과 of 의 더 자세한 버전
(ex) `BigInteger prime = BigInteger.valueOf(Integer.MAX_VALUE);`

4. instance / getInstance : 매개변수로 명시한 인스턴스를 반환하지만, 같은 인스턴스임을 보장하지는 않는다.
(ex) `StackWalker luke = StackWalker.getInstance(options);`

5. create / newInstance : instance 혹은 getInstance와 같지만, 매번 새로운 인스턴스를 생성해 반환함을 보장한다.
(ex) `Object newArray = Array.newInstance(classObject, arrayLen);`
_**-> 이러면 장점 2번을 만족하지 못하는 거 아닌가?..**_

6. getType : getInstance 와 같으나, 생성할 클래스가 아닌 다른 클래스에 팩터리 메서드를 정의할 때 쓴다.  "Type"은 팩터리 메서드가 반환할 객체의 타입이다.
(ex) `FileStore fs = Files.getFileStore(path);`

7. newType : newInstance 와 같으나, 생성할 클래스가 아닌 다른 클래스에 팩터리 메서드를 정의할 때 쓴다. "Type"은 팩터리 메서드가 반환할 객체의 타입이다.
(ex) `BufferedReader br = Files.newBufferedReader(path);`

8. type : getType 과 newType 의 간결한 버전
(ex) `List<Complaint> litany = Collections.list(legacyLitany);`

### 핵심 정리
**정적 팩터리 메서드와 public 생성자는 각자의 쓰임새가 있으니 상대적인 장단점을 이해하고 사용하는 것이 좋다.
그렇다고 하더라도 정적 팩터리를 사용하는 게 유리한 경우가 더 많으므로 무작정 public 생성자를 제공하던 습관이 있다면 고치자.**

**Comment by monkeyDugi** [comment]
> p.9 `불변 값 클래스에서 동치인 인스턴스가 단 하나뿐임을 보장할 수 있다`

플라이 웨이트 패턴과 같은 기법으로 볼 수 있겠죠? 책에는 그렇게 나와 있는 것 같아요 ㅋ.ㅋ

**Comment by monkeyDugi** [comment]
> p.10 네 번째 장점에서 `입력 매개변수에 따라 매번 다른 클래스의 객체를 반환할 수 있다.`

결국 세 번째 장점에서 매개 변수로 구분만 한다는 차이겠죠?

**Comment by monkeyDugi** [comment]
플라이 웨이트 패턴이 언급되는데 그 이유가 아래와 같다고 하네요
플라이 웨이트 패턴은 메모리 사용량을 줄이기 위해 미리 필요한 객체들을 캐싱 해놓고, 제가 좀 정리했는데 참고 하시면 좋을 거 같아요!!

https://www.notion.so/bigin/25a6c131833f456da35c7d9209cfa259

**Comment by monkeyDugi** [comment]
플라이 웨이트 패턴이 언급되는데 그 이유가 아래와 같다고 하네요
플라이 웨이트 패턴은 메모리 사용량을 줄이기 위해 미리 필요한 객체들을 캐싱 해놓고, 제가 좀 정리했는데 참고 하시면 좋을 거 같아요!!

https://www.notion.so/bigin/25a6c131833f456da35c7d9209cfa259

**Comment by junho-bigin** [comment]
정적 팩터리 메서드에서의 명명 방식

이거 되게 도움 되겠네요.

**Comment by monkeyDugi** [comment]
> 정적 팩터리 메서드에서의 명명 방식
> 
> 이거 되게 도움 되겠네요.

컨벤션으로 바로 문서 만들어서 가볼까요?
바로 쉽게 적용할 수 있는 부분 같은데요?

**Comment by Kimjaeyeon518** [comment]
> > p.9 `불변 값 클래스에서 동치인 인스턴스가 단 하나뿐임을 보장할 수 있다`
> 
> 플라이 웨이트 패턴과 같은 기법으로 볼 수 있겠죠? 책에는 그렇게 나와 있는 것 같아요 ㅋ.ㅋ

동치인 인스턴스가 단 하나뿐임을 보장할 수 있다는 말에서 2가지 장점이 파생되는 것 같아요
1. 플라이 웨이트 패턴을 썼을 때의 장점 (메모리 절약)
2. '==' 연산자를 .equals() 와 같은 연산으로 사용할 수 있기 위하여

**Comment by Kimjaeyeon518** [comment]
> > p.10 네 번째 장점에서 `입력 매개변수에 따라 매번 다른 클래스의 객체를 반환할 수 있다.`
> 
> 결국 세 번째 장점에서 매개 변수로 구분만 한다는 차이겠죠?

결국 비슷한 얘기긴 한데

굳이 나누자면 아래 코드에서

```
public class Item{

    public static Item getItemByType(String type){
        if(type.equals("ONLINE"){
            return new OnlineItem();
        } else if(type.equals("DEPARTMENT_STORE")){
            return new DptsItem();
        }
        
        new IllegalArgumentException("잘못된 타입입니다.");
    }

}

```
3번째 장점은 'Item' 을 상속받는 하위 타입인 'OnlineItem', 'DptsItem' 을 반환할 수 있다는 얘기고,

4번째 장점은 매개변수인 'type' 값에 대하여 분기 처리를 하였을 때,

```
if (type == "1") {
    new Item(1);
} else {
    new Item(2);
}
```
과 같이 같은 클래스지만 동치가 아닌 클래스를 반환 가능하다는 것 같습니다 (억빠)

**Comment by monkeyDugi** [comment]
> 과 같이 같은 클래스지만 동치가 아닌 클래스를 반환 가능하다는 것 같습니다 (억빠) 

ㅋ.ㅋ.ㅋ 억빠 ㅋㅋㅋㅋ

**Comment by monkeyDugi** [comment]
@Kimjaeyeon518 @junho-bigin 
제가 컨벤션 작성하고 close 할게요
