### ISSUE TITLE
아이템 3. private 생성자나 열거 타입으로 싱글턴임을 보증하라

### ISSUE THREAD

**Issue by junho-bigin** [Bigin-Study/effective-java#2]
**Questions**
1. readResolve란 메서드는 무엇인가? Object class에 존재하는 것일까?
> [24p] 가짜 Elvis 탄생을 예방하고 싶다면 Elvis 클래스에 다음의 readResolve 메서드를 추가하자.

**Comment by monkeyDugi** [comment]
> readResolve 메서드란 무엇인가?

아이템 89(더 좋은 이해를 위해서는 87, 88까지) 참고하면 될 것 같은데 제대로 보지 못했네요 ㅜ.ㅜ
오늘 같이 보면 좋을 것 같아요! 더 자세한 내용을 알고 싶다면, `ObjectInputStream`을 디버깅 해보면 될 것 같아요!
![스크린샷 2023-02-01 오전 7 54 02](https://user-images.githubusercontent.com/53487385/215902494-cc4519fd-d2db-49e1-b9d1-1865a3400b92.png)

> Object class에 존재하는가?

존재하는 것이 아닌 것 같습니다.
ObjectInputStream.java가 역직렬화를 하는데 `private Object readOrdinaryObject(boolean unshared)`에서 진행하는 것 같습니다.
이때 내부적으로 `invokeReadResolve()`를 하는데 이는 `ObjectStreamClass.java`에 존재합니다.
그리고 `ObjectStreamClass.java`를 생성할 때 아래와 같이 리플렉션을 사용해서 메서드가 존재하는지 찾는 방식으로 판단됩니다.
디버깅도 해보고 싶었는데 시간이 없어서 못해봤네요 ㅜ.ㅜ
```java
readResolveMethod = getInheritableMethod(
                        cl, "readResolve", null, Object.class);
                    return null;
```

> readObject란?

내부적으로 readResolve가 있는지 체크한다.
그러면 선언이 되어 있다면, readResolve를 호출하는 것이고 없으면 안하는 것이다.
결국 클라이언트가 readResolve를 선언 하느냐 마느냐가 중요하다.

**Comment by monkeyDugi** [comment]
### trasient를 왜 선언해야 하는가

필요없다면 제거하면 된다. 필요 있다면 선언하고 직렬화 역직렬화를 하면 된다.

하지만 통제를 위해서 readResolve 메서드를 선언해서 통제하는 것이다.

### 그렇다면 없으면 도대체 직렬화를 왜 하는가?에 대한 고민이 있었다.

직렬화라는게 결국 필드를 사용하기 위해서 하는 것인데 예로 Json이 되겠다.

그렇다면 필드를 직렬화 하지 않는다면 왜 직렬화 역직렬화를 할까?

예를 하나 들어보면 AMQP가 될 수 있다. AMQP와 두 서버의 통신의 절차로 알아보자.

1. producer 서버는 직렬화해서 AMQP에 보낸다.
2. 컨수머 서버는 AMQP에서 pull한다.
3. 컨수머 서버는 이를 역직렬화 한다.

3번 절차에서 만약 컨수머는 데이터가 필요있는 것이 아니고 그냥 컨숨만 하고 싶을 경우라면

사용할 수 있다. 이때 readResolve 메서드를 선언하면 캐싱된 값을 사용하도록 할 수 있다.
