### ISSUE TITLE
아이템 1. 생성자 대신 정적 팩터리 메서드를 고려하라

### ISSUE THREAD

**Issue by junho-bigin** [Bigin-Study/effective-java#3]
**Questions**
1. 정적 팩터리 메서드와 의존성 주입은 동시에 사용이 가능할까?
2. 아래 문단이 무슨 이야기를 하고 싶은건지 잘 이해가 되지 않는다.
> [10p] 예컨대 자바 컬렉션 프레임워크는 ... 물론 이는 일반적으로 좋은 습관이다.
3. ServiceLoader 클래스란 무엇이고, 가벼운 예제는 어떤 것이 있을까?
> [12p] 자바 5부터는 java.util.ServiceLoader라는 범용 서비스 제공자 프레임워크가 제공되어 프레임워크를 직접 만들 필요가 거의 없어졌다.

**Comment by junho-bigin** [comment]
1. 가능하다
```
@Configuration
public class AwsConfig {
  @Bean
  public AmazonS3 amazonS3() {
    return AmazonS3.create("BLAH BLAH");
  }
}
```

**Comment by junho-bigin** [comment]
2. Collections 하위 클래스가 뭐가 있는지 알 필요가 없이, Collections.XXX()로 하위 클래스를 인스턴스화 할 수 있는 다양한 형태의 객체를 제공해줄 수 있다.
```
import java.util.Collections;
import java.util.List;

class Scratch {

  public static void main(String[] args) {
    List<Object> emptyList = Collections.emptyList();
  }
}
```

**Comment by Kimjaeyeon518** [comment]
3. ServiceLoader : interface를 구현하고 있는 구현체가 내부에 작성되어 있다면 interface를 그 구현체로써 쓸 수 있게 해준다

참고자료
- https://www.baeldung.com/java-spi

@monkeyDugi 
추가 설명
예상이긴 하지만 DriverManager나 Slf4j 등 인터페이스를 두고 라이브러리를 클래스 패스에서 읽어오는 것을 의미하는 것 같다.
DriverManager는 내부적으로 JDBC 인터페이스를 참조하고, 이 아래로 Orace Driver, MySQL Driver등 라이브러리의 클래스 패스를
읽어서 interator하여 참조하게 된다. 결국 java는 내부적으로 ServiceLoader(ver 1.6+)를 사용해서 이 행위를 하는 것이다.
