### ISSUE TITLE
아이템 4. 인스턴스화를 막으려거든 private 생성자를 사용하라

### ISSUE THREAD

**Issue by junho-bigin** [Bigin-Study/effective-java#5]
**Eureka**
- throw까지 날려주니까 더 좋은것 같다.
> [26p] 코드 4-1 인스턴스를 만들 수 없는 유틸리티 클래스
> ```java
> class UtilityClass {
>   // 기본 생성자가 만들어지는 것을 막는다(인스턴스화 방지용).
>   private UtilityClass() {
>     throw new AssertionError();
>   }
> }
> ```

**Comment by monkeyDugi** [comment]
인정!
