### ISSUE TITLE
2. 생성자에 매개변수가 많다면 빌더를 고려하라.

### ISSUE THREAD

**Issue by monkeyDugi** [Bigin-Study/effective-java#9]
### 질문1
> p.19 불변은 String과 같이 절대 값을 바꿀 수 없다. 불변식은 변경은 가능하나 주어진 조건 내에서만 허용한다.

빌더 패턴은 불변이다. 불변식과는 다르다. 그러면 Entity는 뭐라고 표현할까요?
불변식이겠죠?

### 질문2
빌더 패턴의 단점으로 어떤 값이 필수인지 알 수가 없지 않나요?
생성자라면 이 값들은 필수라는 것을 컴파일 에러로 알 수 있는데 빌더는 런타임때 알 수 있는 것 같아요!

**Comment by Kimjaeyeon518** [comment]
1. 네 불변식입니다.
2. 넵!!
